//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.crChangeRequestWatchers = new HashSet<crChangeRequestWatcher>();
            this.DesignationMappings = new HashSet<DesignationMapping>();
            this.TriggerPointUsers = new HashSet<TriggerPointUser>();
        }
    
        public string Id { get; set; }
        public Nullable<int> OldId { get; set; }
        public string DisplayName { get; set; }
        public string Culture { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> TitleId { get; set; }
        public short GenderId { get; set; }
        public string MiddleName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public short CountryId { get; set; }
        public string ZipCode { get; set; }
        public int RoleId { get; set; }
        public bool Active { get; set; }
        public bool IsRFQCoordinator { get; set; }
        public System.DateTime NextSystemMessageDisplayDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public bool IsDeleted { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<crChangeRequestWatcher> crChangeRequestWatchers { get; set; }
        public virtual ICollection<DesignationMapping> DesignationMappings { get; set; }
        public virtual ICollection<TriggerPointUser> TriggerPointUsers { get; set; }
    }
}
