//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSubElementDetail
    {
        public AssessmentSubElementDetail()
        {
            this.AssessmentSubElementValues = new HashSet<AssessmentSubElementValue>();
        }
    
        public int Id { get; set; }
        public int DetailId { get; set; }
        public string SubElementDetail { get; set; }
        public string SubElementDetail_Chinese { get; set; }
        public int SortOrder { get; set; }
        public string DataType { get; set; }
    
        public virtual ICollection<AssessmentSubElementValue> AssessmentSubElementValues { get; set; }
        public virtual AssessmentElementDetail AssessmentElementDetail { get; set; }
    }
}
