//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentElement
    {
        public AssessmentElement()
        {
            this.AssessmentElementDetails = new HashSet<AssessmentElementDetail>();
        }
    
        public int Id { get; set; }
        public string ElementName { get; set; }
        public string ElementName_Chinese { get; set; }
        public int QuestionTypeId { get; set; }
    
        public virtual AssessmentQuestionType AssessmentQuestionType { get; set; }
        public virtual ICollection<AssessmentElementDetail> AssessmentElementDetails { get; set; }
    }
}
