//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentElementDetail
    {
        public AssessmentElementDetail()
        {
            this.AssessmentElementValues = new HashSet<AssessmentElementValue>();
            this.AssessmentSubElementDetails = new HashSet<AssessmentSubElementDetail>();
        }
    
        public int Id { get; set; }
        public int ElementId { get; set; }
        public string ElementDetail { get; set; }
        public string ElementDetail_Chinese { get; set; }
        public Nullable<bool> SubElement { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<bool> IsOptionAvailable { get; set; }
    
        public virtual AssessmentElement AssessmentElement { get; set; }
        public virtual ICollection<AssessmentElementValue> AssessmentElementValues { get; set; }
        public virtual ICollection<AssessmentSubElementDetail> AssessmentSubElementDetails { get; set; }
    }
}
