//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentElementValue
    {
        public int AssessmentId { get; set; }
        public int DetailId { get; set; }
        public Nullable<int> Score { get; set; }
        public string Observations { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string OptionValue { get; set; }
    
        public virtual AssessmentElementDetail AssessmentElementDetail { get; set; }
        public virtual SupplierAssessment SupplierAssessment { get; set; }
    }
}
