//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociatedTo
    {
        public AssociatedTo()
        {
            this.DocumentTypeAssociatedToes = new HashSet<DocumentTypeAssociatedTo>();
            this.StatusAssociatedToes = new HashSet<StatusAssociatedTo>();
            this.RemarksAssociatedToes = new HashSet<RemarksAssociatedTo>();
            this.apqpDocuments = new HashSet<apqpDocument>();
        }
    
        public int Id { get; set; }
        public string AssociatedTo1 { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Source { get; set; }
    
        public virtual ICollection<DocumentTypeAssociatedTo> DocumentTypeAssociatedToes { get; set; }
        public virtual ICollection<StatusAssociatedTo> StatusAssociatedToes { get; set; }
        public virtual ICollection<RemarksAssociatedTo> RemarksAssociatedToes { get; set; }
        public virtual ICollection<apqpDocument> apqpDocuments { get; set; }
    }
}
