//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class capaQuery
    {
        public capaQuery()
        {
            this.capaRootCauseWhyMades = new HashSet<capaRootCauseWhyMade>();
            this.capaRootCauseWhyShippeds = new HashSet<capaRootCauseWhyShipped>();
            this.capaProblemDescriptions = new HashSet<capaProblemDescription>();
        }
    
        public short Id { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<capaRootCauseWhyMade> capaRootCauseWhyMades { get; set; }
        public virtual ICollection<capaRootCauseWhyShipped> capaRootCauseWhyShippeds { get; set; }
        public virtual ICollection<capaProblemDescription> capaProblemDescriptions { get; set; }
    }
}
