//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class capaPartAffectedDetail
    {
        public capaPartAffectedDetail()
        {
            this.capaPartDocuments = new HashSet<capaPartDocument>();
        }
    
        public int Id { get; set; }
        public int CorrectiveActionId { get; set; }
        public Nullable<int> DefectTypeId { get; set; }
        public Nullable<int> APQPItemId { get; set; }
        public string PartName { get; set; }
        public Nullable<System.DateTime> ActualCompletedDate { get; set; }
        public Nullable<int> CustomerRejectedPartQty { get; set; }
        public Nullable<int> SupplierRejectedPartQty { get; set; }
        public Nullable<int> PartsDeliveryLateQty { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual capaItemMaster capaItemMaster { get; set; }
        public virtual DefectType DefectType { get; set; }
        public virtual ICollection<capaPartDocument> capaPartDocuments { get; set; }
    }
}
