//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class capaItemMaster
    {
        public capaItemMaster()
        {
            this.capaApprovals = new HashSet<capaApproval>();
            this.capaFeedForwards = new HashSet<capaFeedForward>();
            this.capaPartAffectedDetails = new HashSet<capaPartAffectedDetail>();
            this.capaPermanentCountermeasures = new HashSet<capaPermanentCountermeasure>();
            this.capaRootCauseWhyMades = new HashSet<capaRootCauseWhyMade>();
            this.capaRootCauseWhyShippeds = new HashSet<capaRootCauseWhyShipped>();
            this.capaTempCountermeasures = new HashSet<capaTempCountermeasure>();
            this.capaVerifications = new HashSet<capaVerification>();
            this.capaProblemDescriptions = new HashSet<capaProblemDescription>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DefectTrackingId { get; set; }
        public string IncludeInPPM { get; set; }
        public string CorrectiveActionType { get; set; }
        public string CorrectiveActionInitiatedBy { get; set; }
        public Nullable<System.DateTime> CorrectiveActionInitiatedDate { get; set; }
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierContactName { get; set; }
        public string ReviewCtrlPlan { get; set; }
        public string ReviewFMEA { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<capaApproval> capaApprovals { get; set; }
        public virtual ICollection<capaFeedForward> capaFeedForwards { get; set; }
        public virtual dtDefectTracking dtDefectTracking { get; set; }
        public virtual ICollection<capaPartAffectedDetail> capaPartAffectedDetails { get; set; }
        public virtual ICollection<capaPermanentCountermeasure> capaPermanentCountermeasures { get; set; }
        public virtual ICollection<capaRootCauseWhyMade> capaRootCauseWhyMades { get; set; }
        public virtual ICollection<capaRootCauseWhyShipped> capaRootCauseWhyShippeds { get; set; }
        public virtual ICollection<capaTempCountermeasure> capaTempCountermeasures { get; set; }
        public virtual ICollection<capaVerification> capaVerifications { get; set; }
        public virtual ICollection<capaProblemDescription> capaProblemDescriptions { get; set; }
    }
}
