//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityTypeSupplier
    {
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public short CommodityTypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CommodityType CommodityType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
