//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts1
    {
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public Nullable<short> PrefixId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Designation { get; set; }
        public string DirectPhone { get; set; }
        public string Extension { get; set; }
        public string DirectFax { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public bool IsDefault { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Prefix Prefix { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
