//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class crChangeRequestWatcher
    {
        public int ChangeRequestId { get; set; }
        public string WatcherId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> OldWatcherId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual crItemMaster crItemMaster { get; set; }
    }
}
