//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CommodityTypeCustomers = new HashSet<CommodityTypeCustomer>();
            this.Divisions = new HashSet<Division>();
            this.Addresses = new HashSet<Address>();
            this.Contacts = new HashSet<Contact>();
            this.RFQs = new HashSet<RFQ>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public string CompanyPhone1 { get; set; }
        public string CompanyPhone2 { get; set; }
        public string CompanyFax { get; set; }
        public string Comments { get; set; }
        public Nullable<short> PaymentRating { get; set; }
        public string CustomerCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> SAMId { get; set; }
        public Nullable<int> OldSAMId { get; set; }
    
        public virtual ICollection<CommodityTypeCustomer> CommodityTypeCustomers { get; set; }
        public virtual ICollection<Division> Divisions { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<RFQ> RFQs { get; set; }
    }
}
