//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Id { get; set; }
        public string QuoteId { get; set; }
        public string QuoteRevision { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public int PartId { get; set; }
        public Nullable<decimal> ToolingCost { get; set; }
        public decimal ShippingCost { get; set; }
        public Nullable<decimal> Warehousing { get; set; }
        public Nullable<decimal> SGAProfit { get; set; }
        public Nullable<decimal> SalesCommission { get; set; }
        public Nullable<decimal> CustomDuties { get; set; }
        public Nullable<decimal> SupplierQuotedPrice { get; set; }
        public string Leadtime { get; set; }
        public string ShippingAssumption { get; set; }
        public Nullable<decimal> SupplierPriceUsed { get; set; }
        public Nullable<decimal> FinalMESPrice { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public Nullable<decimal> TotalAnnualCost { get; set; }
        public Nullable<decimal> SupplierCostPerKg { get; set; }
        public Nullable<decimal> FinalMESCostPerKg { get; set; }
        public string SupplierToolingLeadtime { get; set; }
        public string ToolingWarranty { get; set; }
        public Nullable<bool> IsAPQPItem { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int MinOrderQty { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
