//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.DocumentTypeAssociatedToes = new HashSet<DocumentTypeAssociatedTo>();
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document1>();
            this.apqpDocuments = new HashSet<apqpDocument>();
            this.crDocuments = new HashSet<crDocument>();
        }
    
        public int Id { get; set; }
        public string DocumentType1 { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsConfidential { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<DocumentTypeAssociatedTo> DocumentTypeAssociatedToes { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Document1> Documents1 { get; set; }
        public virtual ICollection<apqpDocument> apqpDocuments { get; set; }
        public virtual ICollection<crDocument> crDocuments { get; set; }
    }
}
