//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class dqSurfaceTreatment
    {
        public int Id { get; set; }
        public Nullable<int> RFQSupplierPartDQId { get; set; }
        public Nullable<int> CoatingTypeId { get; set; }
        public string CoatingType { get; set; }
        public Nullable<int> PartsPerHour { get; set; }
        public Nullable<decimal> ManPlusMachineRatePerHour { get; set; }
        public Nullable<decimal> CoatingCostPerHour { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SupplierPartQuote SupplierPartQuote { get; set; }
    }
}
