//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtDefectTracking
    {
        public dtDefectTracking()
        {
            this.capaItemMasters = new HashSet<capaItemMaster>();
        }
    
        public int Id { get; set; }
        public string IncludeInPPM { get; set; }
        public string Finding { get; set; }
        public string QualityOrDeliveryIssue { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string RMANumber { get; set; }
        public Nullable<System.DateTime> RMADate { get; set; }
        public string RMAInitiatedBy { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OldRMAInitiatedById { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<capaItemMaster> capaItemMasters { get; set; }
    }
}
