//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPIFDocusign
    {
        public NPIFDocusign()
        {
            this.NPIFDocuSignApprovers = new HashSet<NPIFDocuSignApprover>();
        }
    
        public int Id { get; set; }
        public Nullable<int> APQPItemId { get; set; }
        public string DocumentId { get; set; }
        public string EnvelopeId { get; set; }
        public string InitialDocumentPath { get; set; }
        public string SignedDocumentPath { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateOfStatus { get; set; }
        public string VoidedReason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual NPIFDocusign NPIFDocusign1 { get; set; }
        public virtual NPIFDocusign NPIFDocusign2 { get; set; }
        public virtual ICollection<NPIFDocuSignApprover> NPIFDocuSignApprovers { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
    }
}
