//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public Object()
        {
            this.Roles = new HashSet<Role>();
            this.UserPreferences = new HashSet<UserPreference>();
        }
    
        public int ObjectId { get; set; }
        public string ObjectName { get; set; }
        public string PageName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsMenuItem { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<bool> CanBeDefault { get; set; }
        public string MenuClass { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
    }
}
