//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prefix
    {
        public Prefix()
        {
            this.Contacts = new HashSet<Contact>();
            this.Contacts1 = new HashSet<Contacts1>();
        }
    
        public short Id { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Contacts1> Contacts1 { get; set; }
    }
}
