//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTracking
    {
        public int Id { get; set; }
        public Nullable<int> APQPItemId { get; set; }
        public Nullable<int> APQPProjectCategoryId { get; set; }
        public Nullable<int> APQPProjectStageId { get; set; }
        public Nullable<System.DateTime> CurrentEstimatedToolingCompletionDate { get; set; }
        public string ShipmentTrackingNumber { get; set; }
        public string QualityFeedbackInformation { get; set; }
        public Nullable<System.DateTime> EstimatedSampleShipmentDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ActualToolingCompletionDate { get; set; }
        public Nullable<System.DateTime> ActualSampleShipmentDate { get; set; }
        public string UpdatedFromSource { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ToolChangeDetails { get; set; }
    }
}
