//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteStatu
    {
        public QuoteStatu()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public short Id { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
