//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.QuoteCalculationHistories = new HashSet<QuoteCalculationHistory>();
            this.Details = new HashSet<Detail>();
        }
    
        public string Id { get; set; }
        public string RFQId { get; set; }
        public string ParentID { get; set; }
        public string QuoteNumber { get; set; }
        public string GeneralAssumption { get; set; }
        public System.DateTime Date { get; set; }
        public bool Revision { get; set; }
        public string SAMId { get; set; }
        public Nullable<decimal> CustomDutiesPercent { get; set; }
        public Nullable<decimal> ShippingCostPercent { get; set; }
        public Nullable<decimal> WarehousingPercent { get; set; }
        public Nullable<decimal> SGAProfitPercent { get; set; }
        public Nullable<decimal> SalesCommissionPercent { get; set; }
        public Nullable<decimal> AmountWon { get; set; }
        public short Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ShippingCostCalMethod { get; set; }
        public Nullable<decimal> SupplierCost { get; set; }
        public string QuoteFilePath { get; set; }
        public string ExtQuoteFilePath { get; set; }
        public string MESComments { get; set; }
        public Nullable<decimal> ToolingCostPercent { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> OldSAMId { get; set; }
    
        public virtual QuoteStatu QuoteStatu { get; set; }
        public virtual ICollection<QuoteCalculationHistory> QuoteCalculationHistories { get; set; }
        public virtual ICollection<Detail> Details { get; set; }
        public virtual RFQ RFQ { get; set; }
    }
}
