//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ
    {
        public RFQ()
        {
            this.Quotes = new HashSet<Quote>();
            this.rfqSuppliers = new HashSet<rfqSupplier>();
        }
    
        public string Id { get; set; }
        public int CustomerId { get; set; }
        public int CustomerContactId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Currency { get; set; }
        public string IngotPriceAssumed { get; set; }
        public string CastPrice { get; set; }
        public string OtherAssumption { get; set; }
        public string ProjectName { get; set; }
        public string RawMaterialPriceAssumed { get; set; }
        public Nullable<System.DateTime> QuoteDueDate { get; set; }
        public string Status { get; set; }
        public string SAMId { get; set; }
        public Nullable<short> CommodityTypeId { get; set; }
        public string ParentId { get; set; }
        public string RFQCoordinatorId { get; set; }
        public Nullable<int> RFQSourceId { get; set; }
        public Nullable<int> RFQTypeId { get; set; }
        public Nullable<int> NonAwardFeedbackId { get; set; }
        public string NonAwardDetailedFeedback { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<System.DateTime> StatusUpdatedDate { get; set; }
        public string Remarks { get; set; }
        public string RfqFilePath { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> oldsamid { get; set; }
        public Nullable<int> oldrfqcoordinatorid { get; set; }
        public string RfqFileName { get; set; }
        public string SupplierRequirement { get; set; }
        public Nullable<short> RFQPriorityId { get; set; }
        public Nullable<short> IndustryTypeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual CommodityType CommodityType { get; set; }
        public virtual RFQPriority RFQPriority { get; set; }
        public virtual Commodity Commodity { get; set; }
        public virtual NonAwardFeedback NonAwardFeedback { get; set; }
        public virtual Process Process { get; set; }
        public virtual RFQType RFQType { get; set; }
        public virtual ICollection<rfqSupplier> rfqSuppliers { get; set; }
        public virtual IndustryType IndustryType { get; set; }
    }
}
