//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfqSupplier
    {
        public rfqSupplier()
        {
            this.SupplierPartQuotes = new HashSet<SupplierPartQuote>();
        }
    
        public int Id { get; set; }
        public string RFQId { get; set; }
        public int SupplierId { get; set; }
        public string UniqueURL { get; set; }
        public Nullable<System.DateTime> QuoteExpireDate { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public bool IsURLActive { get; set; }
        public string Remarks { get; set; }
        public string OriginalURL { get; set; }
        public Nullable<bool> NoQuote { get; set; }
        public Nullable<bool> IsQuoteTypeDQ { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<SupplierPartQuote> SupplierPartQuotes { get; set; }
        public virtual RFQ RFQ { get; set; }
    }
}
