//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleObjectPrivilege
    {
        public int RoleId { get; set; }
        public int ObjectId { get; set; }
        public int PrivilegeId { get; set; }
        public Nullable<bool> HasPricingFieldsAccess { get; set; }
        public Nullable<bool> AllowDeleteRecord { get; set; }
        public Nullable<bool> AllowConfidentialDocumentType { get; set; }
        public Nullable<bool> AllowExportToSAP { get; set; }
        public int Id { get; set; }
        public Nullable<bool> AllowSendDataToSAP { get; set; }
        public Nullable<bool> AllowCheckNPIFStatus { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Privilege Privilege { get; set; }
    }
}
