//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleObjectPrivileges = new HashSet<RoleObjectPrivilege>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public bool Active { get; set; }
        public int DefaultObjectId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<RoleObjectPrivilege> RoleObjectPrivileges { get; set; }
        public virtual Object Object { get; set; }
    }
}
