//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    
    public partial class SearchRFQSuppliers_Result1
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Website { get; set; }
        public string CompanyPhone1 { get; set; }
        public Nullable<bool> IsQuoteTypeDQ { get; set; }
        public string UniqueURL { get; set; }
        public string OriginalURL { get; set; }
        public string RFQId { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
    }
}
