//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.Documents = new HashSet<Document1>();
            this.POParts = new HashSet<POPart>();
            this.ShipmentSuppliers = new HashSet<ShipmentSupplier>();
        }
    
        public int Id { get; set; }
        public short DestinationId { get; set; }
        public short ForwarderId { get; set; }
        public Nullable<System.DateTime> EstShpmntDate { get; set; }
        public Nullable<System.DateTime> ActShpmntDate { get; set; }
        public Nullable<System.DateTime> ETAAtWarehouseAtDest { get; set; }
        public Nullable<System.DateTime> ActArrDateAtWarehouseAtDest { get; set; }
        public Nullable<System.DateTime> EstForwarderPickupDate { get; set; }
        public Nullable<System.DateTime> ActForwarderPickupDate { get; set; }
        public bool LateDeliveryToForwarder { get; set; }
        public string Inspector { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string InspectionReportFilePath { get; set; }
        public short ShipmentMode { get; set; }
        public Nullable<short> QualityReviewStatus { get; set; }
        public string QualityReviewComments { get; set; }
        public Nullable<short> OriginId { get; set; }
        public bool Status { get; set; }
        public string ContainerNumber { get; set; }
        public string InvoiceNumbers { get; set; }
        public bool ShipmentReviewed { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string InspectionReportFileName { get; set; }
    
        public virtual Forwarder Forwarder { get; set; }
        public virtual Origin Origin { get; set; }
        public virtual ICollection<Document1> Documents { get; set; }
        public virtual ICollection<POPart> POParts { get; set; }
        public virtual ICollection<ShipmentSupplier> ShipmentSuppliers { get; set; }
    }
}
