//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.StatusAssociatedToes = new HashSet<StatusAssociatedTo>();
            this.crItemMasters = new HashSet<crItemMaster>();
            this.ItemMasters = new HashSet<ItemMaster>();
        }
    
        public int Id { get; set; }
        public string Status1 { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<StatusAssociatedTo> StatusAssociatedToes { get; set; }
        public virtual ICollection<crItemMaster> crItemMasters { get; set; }
        public virtual ICollection<ItemMaster> ItemMasters { get; set; }
    }
}
