//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPartQuote
    {
        public SupplierPartQuote()
        {
            this.dqMachiningOtherOperations = new HashSet<dqMachiningOtherOperation>();
            this.dqMachiningSecondaryOperations = new HashSet<dqMachiningSecondaryOperation>();
            this.dqOverheads = new HashSet<dqOverhead>();
            this.dqPrimaryProcessConversions = new HashSet<dqPrimaryProcessConversion>();
            this.dqSurfaceTreatments = new HashSet<dqSurfaceTreatment>();
            this.dqRawMaterials = new HashSet<dqRawMaterial>();
        }
    
        public int Id { get; set; }
        public int RFQSupplierId { get; set; }
        public int RFQPartId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> ProcessCost { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> ToolingCost { get; set; }
        public string Currency { get; set; }
        public string RawMaterialPriceAssumed { get; set; }
        public string QuoteAttachmentFilePath { get; set; }
        public Nullable<decimal> MachiningCost { get; set; }
        public Nullable<decimal> OtherProcessCost { get; set; }
        public string Remarks { get; set; }
        public string SupplierToolingLeadtime { get; set; }
        public string ToolingWarranty { get; set; }
        public Nullable<int> NoOfCavities { get; set; }
        public Nullable<int> MinOrderQty { get; set; }
        public Nullable<bool> MOQConfirmation { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual rfqSupplier rfqSupplier { get; set; }
        public virtual ICollection<dqMachiningOtherOperation> dqMachiningOtherOperations { get; set; }
        public virtual ICollection<dqMachiningSecondaryOperation> dqMachiningSecondaryOperations { get; set; }
        public virtual ICollection<dqOverhead> dqOverheads { get; set; }
        public virtual ICollection<dqPrimaryProcessConversion> dqPrimaryProcessConversions { get; set; }
        public virtual ICollection<dqSurfaceTreatment> dqSurfaceTreatments { get; set; }
        public virtual ICollection<dqRawMaterial> dqRawMaterials { get; set; }
    }
}
