//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Data.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolingLaunch
    {
        public int Id { get; set; }
        public Nullable<int> APQPItemId { get; set; }
        public string MESToolingPONumber { get; set; }
        public string RevLevel { get; set; }
        public Nullable<System.DateTime> ToolingKickoffDate { get; set; }
        public Nullable<System.DateTime> PlanToolingCompletionDate { get; set; }
        public string APQPDrawingStatus { get; set; }
        public Nullable<int> PPAPSubmissonPreparationDays { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public string UpdatedFromSource { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
