//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.DTO.Library.Base.Messaging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DTOMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DTOMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MES.DTO.Library.Base.Messaging.Resources.DTOMessageResources", typeof(DTOMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address is deleted successfully..
        /// </summary>
        internal static string AddressDeletedSuccess {
            get {
                return ResourceManager.GetString("AddressDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can not be deleted due to some error..
        /// </summary>
        internal static string AddressDeleteFail {
            get {
                return ResourceManager.GetString("AddressDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address does not exist..
        /// </summary>
        internal static string AddressNotExists {
            get {
                return ResourceManager.GetString("AddressNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address is saved successfully..
        /// </summary>
        internal static string AddressSavedSuccess {
            get {
                return ResourceManager.GetString("AddressSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request details added to APQP successfully..
        /// </summary>
        internal static string AddToAPQPSuccess {
            get {
                return ResourceManager.GetString("AddToAPQPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been deleted successfully..
        /// </summary>
        internal static string APQPDeletedSuccess {
            get {
                return ResourceManager.GetString("APQPDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cannot be deleted..
        /// </summary>
        internal static string APQPDeleteFail {
            get {
                return ResourceManager.GetString("APQPDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is deleted successfully..
        /// </summary>
        internal static string APQPDocumentDeletedSuccess {
            get {
                return ResourceManager.GetString("APQPDocumentDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document can not be deleted..
        /// </summary>
        internal static string APQPDocumentFailedSuccess {
            get {
                return ResourceManager.GetString("APQPDocumentFailedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document does not exist..
        /// </summary>
        internal static string APQPDocumentNotExists {
            get {
                return ResourceManager.GetString("APQPDocumentNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is saved successfully..
        /// </summary>
        internal static string APQPDocumentSavedSuccess {
            get {
                return ResourceManager.GetString("APQPDocumentSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APQP data is saved successfully..
        /// </summary>
        internal static string APQPSavedSuccess {
            get {
                return ResourceManager.GetString("APQPSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APQP data can not be saved..
        /// </summary>
        internal static string APQPSaveFail {
            get {
                return ResourceManager.GetString("APQPSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Assessment saved successfully..
        /// </summary>
        internal static string AssessmentSavedSuccess {
            get {
                return ResourceManager.GetString("AssessmentSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please associate user(s) with respective Trigger Point in email group to send &apos;APQP Email&apos;..
        /// </summary>
        internal static string AssociateuserwtihTriggerPoint {
            get {
                return ResourceManager.GetString("AssociateuserwtihTriggerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Analysis (QTC) Report Template does not exists..
        /// </summary>
        internal static string BusinessAnalysisQTCReportTemplateNotExists {
            get {
                return ResourceManager.GetString("BusinessAnalysisQTCReportTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessAnalysisReport(QTC).
        /// </summary>
        internal static string BusinessAnalysisReportQTCFileName {
            get {
                return ResourceManager.GetString("BusinessAnalysisReportQTCFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Analysis Report (QTC).
        /// </summary>
        internal static string BusinessAnalysisReportQTCSheetName {
            get {
                return ResourceManager.GetString("BusinessAnalysisReportQTCSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Analysis Report Template does not exists..
        /// </summary>
        internal static string BusinessAnalysisReportTemplateNotExists {
            get {
                return ResourceManager.GetString("BusinessAnalysisReportTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPA is deleted successfully..
        /// </summary>
        internal static string CAPADeletedSuccess {
            get {
                return ResourceManager.GetString("CAPADeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPA can not be deleted due to some error..
        /// </summary>
        internal static string CAPADeleteFailed {
            get {
                return ResourceManager.GetString("CAPADeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPA does not exist..
        /// </summary>
        internal static string CAPANotExists {
            get {
                return ResourceManager.GetString("CAPANotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPA is saved successfully..
        /// </summary>
        internal static string CAPASavedSuccess {
            get {
                return ResourceManager.GetString("CAPASavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPA can not be saved..
        /// </summary>
        internal static string CAPASaveFail {
            get {
                return ResourceManager.GetString("CAPASaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required..
        /// </summary>
        internal static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Please try again..
        /// </summary>
        internal static string ChangePassword_Failed {
            get {
                return ResourceManager.GetString("ChangePassword_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Old-Password is not valid. Please enter your current password in Old-Password field..
        /// </summary>
        internal static string ChangePassword_InvalidOldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send email. Password has been changed successfully. Please Login with Updated Credentials..
        /// </summary>
        internal static string ChangePassword_SendMailFailure {
            get {
                return ResourceManager.GetString("ChangePassword_SendMailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully. Please Login with Updated Credentials..
        /// </summary>
        internal static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating type is deleted successfully..
        /// </summary>
        internal static string CoatingTypeDeletedSuccess {
            get {
                return ResourceManager.GetString("CoatingTypeDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating type already exists..
        /// </summary>
        internal static string CoatingTypeExists {
            get {
                return ResourceManager.GetString("CoatingTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating type length should not be greater than 100 character..
        /// </summary>
        internal static string CoatingTypeLength {
            get {
                return ResourceManager.GetString("CoatingTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating type does not exist..
        /// </summary>
        internal static string CoatingTypeNotExists {
            get {
                return ResourceManager.GetString("CoatingTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating type is required..
        /// </summary>
        internal static string CoatingTypeRequired {
            get {
                return ResourceManager.GetString("CoatingTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating type is saved successfully..
        /// </summary>
        internal static string CoatingTypeSavedSuccess {
            get {
                return ResourceManager.GetString("CoatingTypeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity is deleted successfully..
        /// </summary>
        internal static string CommodityDeletedSuccess {
            get {
                return ResourceManager.GetString("CommodityDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity already exists..
        /// </summary>
        internal static string CommodityExists {
            get {
                return ResourceManager.GetString("CommodityExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity length should not be greater than 100 character..
        /// </summary>
        internal static string CommodityLength {
            get {
                return ResourceManager.GetString("CommodityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity does not exist..
        /// </summary>
        internal static string CommodityNotExists {
            get {
                return ResourceManager.GetString("CommodityNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity is required..
        /// </summary>
        internal static string CommodityRequired {
            get {
                return ResourceManager.GetString("CommodityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity is saved successfully..
        /// </summary>
        internal static string CommoditySavedSuccess {
            get {
                return ResourceManager.GetString("CommoditySavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity type is deleted successfully..
        /// </summary>
        internal static string CommodityTypeDeletedSuccess {
            get {
                return ResourceManager.GetString("CommodityTypeDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity type already exists..
        /// </summary>
        internal static string CommodityTypeExists {
            get {
                return ResourceManager.GetString("CommodityTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity type length should not be greater than 100 character..
        /// </summary>
        internal static string CommodityTypeLength {
            get {
                return ResourceManager.GetString("CommodityTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity type does not exist..
        /// </summary>
        internal static string CommodityTypeNotExists {
            get {
                return ResourceManager.GetString("CommodityTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity type is required..
        /// </summary>
        internal static string CommodityTypeRequired {
            get {
                return ResourceManager.GetString("CommodityTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity type is saved successfully..
        /// </summary>
        internal static string CommodityTypeSavedSuccess {
            get {
                return ResourceManager.GetString("CommodityTypeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact can not be deleted due to some error..
        /// </summary>
        internal static string ContactDeleteFail {
            get {
                return ResourceManager.GetString("ContactDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact(s) is deleted successfully..
        /// </summary>
        internal static string ContactsDeletedSuccess {
            get {
                return ResourceManager.GetString("ContactsDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact does not exist..
        /// </summary>
        internal static string ContactsNotExists {
            get {
                return ResourceManager.GetString("ContactsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is saved successfully..
        /// </summary>
        internal static string ContactsSavedSuccess {
            get {
                return ResourceManager.GetString("ContactsSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request details added to APQP successfully..
        /// </summary>
        internal static string CRAddedToAPQPSuccess {
            get {
                return ResourceManager.GetString("CRAddedToAPQPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Change Request is  deleted successfully..
        /// </summary>
        internal static string CRDeletedSuccess {
            get {
                return ResourceManager.GetString("CRDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request delete failed..
        /// </summary>
        internal static string CRDeleteFailed {
            get {
                return ResourceManager.GetString("CRDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create an email template to send APQP Email..
        /// </summary>
        internal static string CreateEmailTemplate {
            get {
                return ResourceManager.GetString("CreateEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request is saved successfully..
        /// </summary>
        internal static string CRSavedSuccess {
            get {
                return ResourceManager.GetString("CRSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request save failed..
        /// </summary>
        internal static string CRSaveFail {
            get {
                return ResourceManager.GetString("CRSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contact does not exists..
        /// </summary>
        internal static string CustomerContactNotExists {
            get {
                return ResourceManager.GetString("CustomerContactNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is not able to delete any Customer, As the selected Customer(s) having one or more contacts..
        /// </summary>
        internal static string CustomerDeleteFail {
            get {
                return ResourceManager.GetString("CustomerDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer(s) is deleted successfully..
        /// </summary>
        internal static string CustomersDeletedSuccess {
            get {
                return ResourceManager.GetString("CustomersDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not exist..
        /// </summary>
        internal static string CustomersNotExists {
            get {
                return ResourceManager.GetString("CustomersNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is saved successfully..
        /// </summary>
        internal static string CustomersSavedSuccess {
            get {
                return ResourceManager.GetString("CustomersSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect tracking data does not exist..
        /// </summary>
        internal static string DefectTrackingNotExists {
            get {
                return ResourceManager.GetString("DefectTrackingNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect type is deleted successfully..
        /// </summary>
        internal static string DefectTypeDeletedSuccess {
            get {
                return ResourceManager.GetString("DefectTypeDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect type already exists..
        /// </summary>
        internal static string DefectTypeExists {
            get {
                return ResourceManager.GetString("DefectTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect type length should not be greater than 100 character..
        /// </summary>
        internal static string DefectTypeLength {
            get {
                return ResourceManager.GetString("DefectTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect type does not exist..
        /// </summary>
        internal static string DefectTypeNotExists {
            get {
                return ResourceManager.GetString("DefectTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect type is required..
        /// </summary>
        internal static string DefectTypeRequired {
            get {
                return ResourceManager.GetString("DefectTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect type is saved successfully..
        /// </summary>
        internal static string DefectTypeSavedSuccess {
            get {
                return ResourceManager.GetString("DefectTypeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is deleted successfully..
        /// </summary>
        internal static string DesignationDeletedSuccess {
            get {
                return ResourceManager.GetString("DesignationDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation already exists..
        /// </summary>
        internal static string DesignationExists {
            get {
                return ResourceManager.GetString("DesignationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation length should not be greater than 100 character..
        /// </summary>
        internal static string DesignationLength {
            get {
                return ResourceManager.GetString("DesignationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation does not exist..
        /// </summary>
        internal static string DesignationNotExists {
            get {
                return ResourceManager.GetString("DesignationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is required..
        /// </summary>
        internal static string DesignationRequired {
            get {
                return ResourceManager.GetString("DesignationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is saved successfully..
        /// </summary>
        internal static string DesignationSavedSuccess {
            get {
                return ResourceManager.GetString("DesignationSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is deleted successfully..
        /// </summary>
        internal static string DestinationDeletedSuccess {
            get {
                return ResourceManager.GetString("DestinationDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination already exists..
        /// </summary>
        internal static string DestinationExists {
            get {
                return ResourceManager.GetString("DestinationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination length should not be greater than 100 character..
        /// </summary>
        internal static string DestinationLength {
            get {
                return ResourceManager.GetString("DestinationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required..
        /// </summary>
        internal static string DestinationLocationRequired {
            get {
                return ResourceManager.GetString("DestinationLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination does not exist..
        /// </summary>
        internal static string DestinationNotExists {
            get {
                return ResourceManager.GetString("DestinationNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is required..
        /// </summary>
        internal static string DestinationRequired {
            get {
                return ResourceManager.GetString("DestinationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is saved successfully..
        /// </summary>
        internal static string DestinationSavedSuccess {
            get {
                return ResourceManager.GetString("DestinationSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division can not be deleted due to some error..
        /// </summary>
        internal static string DivisionDeleteFail {
            get {
                return ResourceManager.GetString("DivisionDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division(s) is deleted successfully..
        /// </summary>
        internal static string DivisionsDeletedSuccess {
            get {
                return ResourceManager.GetString("DivisionsDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division does not exist..
        /// </summary>
        internal static string DivisionsNotExists {
            get {
                return ResourceManager.GetString("DivisionsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division is saved successfully..
        /// </summary>
        internal static string DivisionsSavedSuccess {
            get {
                return ResourceManager.GetString("DivisionsSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is deleted successfully..
        /// </summary>
        internal static string DocumentTypeDeletedSuccess {
            get {
                return ResourceManager.GetString("DocumentTypeDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type already exists..
        /// </summary>
        internal static string DocumentTypeExists {
            get {
                return ResourceManager.GetString("DocumentTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type length should not be greater than 100 character..
        /// </summary>
        internal static string DocumentTypeLength {
            get {
                return ResourceManager.GetString("DocumentTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type does not exist..
        /// </summary>
        internal static string DocumentTypeNotExists {
            get {
                return ResourceManager.GetString("DocumentTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is required..
        /// </summary>
        internal static string DocumentTypeRequired {
            get {
                return ResourceManager.GetString("DocumentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is saved successfully..
        /// </summary>
        internal static string DocumentTypeSavedSuccess {
            get {
                return ResourceManager.GetString("DocumentTypeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Number updated successfully..
        /// </summary>
        internal static string DrawingNumberSuccess {
            get {
                return ResourceManager.GetString("DrawingNumberSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect tracking data is deleted successfully..
        /// </summary>
        internal static string DTDeletedSuccess {
            get {
                return ResourceManager.GetString("DTDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect tracking data can not be deleted due to some error..
        /// </summary>
        internal static string DTDeleteFailed {
            get {
                return ResourceManager.GetString("DTDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect tracking data is saved successfully..
        /// </summary>
        internal static string DTSavedSuccess {
            get {
                return ResourceManager.GetString("DTSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect tracking data can not be saved..
        /// </summary>
        internal static string DTSaveFail {
            get {
                return ResourceManager.GetString("DTSaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email subject length should not be greater than 100 character..
        /// </summary>
        internal static string EmailSubjectLength {
            get {
                return ResourceManager.GetString("EmailSubjectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email subject is required..
        /// </summary>
        internal static string EmailSubjectRequired {
            get {
                return ResourceManager.GetString("EmailSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template is deleted successfully..
        /// </summary>
        internal static string EmailTemplateDeletedSuccess {
            get {
                return ResourceManager.GetString("EmailTemplateDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template does not exist..
        /// </summary>
        internal static string EmailTemplateNotExists {
            get {
                return ResourceManager.GetString("EmailTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template is saved successfully..
        /// </summary>
        internal static string EmailTemplateSavedSuccess {
            get {
                return ResourceManager.GetString("EmailTemplateSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the mandatory data in the excel file and upload..
        /// </summary>
        internal static string FillReqData {
            get {
                return ResourceManager.GetString("FillReqData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder is deleted successfully..
        /// </summary>
        internal static string ForwarderDeletedSuccess {
            get {
                return ResourceManager.GetString("ForwarderDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder already exists..
        /// </summary>
        internal static string ForwarderExists {
            get {
                return ResourceManager.GetString("ForwarderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder length should not be greater than 100 character..
        /// </summary>
        internal static string ForwarderNameLength {
            get {
                return ResourceManager.GetString("ForwarderNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder is required..
        /// </summary>
        internal static string ForwarderNameRequired {
            get {
                return ResourceManager.GetString("ForwarderNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder does not exist..
        /// </summary>
        internal static string ForwarderNotExists {
            get {
                return ResourceManager.GetString("ForwarderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder is saved successfully..
        /// </summary>
        internal static string ForwarderSavedSuccess {
            get {
                return ResourceManager.GetString("ForwarderSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Type is deleted successfully..
        /// </summary>
        internal static string IndustryTypeDeletedSuccess {
            get {
                return ResourceManager.GetString("IndustryTypeDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Type already exists..
        /// </summary>
        internal static string IndustryTypeExists {
            get {
                return ResourceManager.GetString("IndustryTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Type does not exist..
        /// </summary>
        internal static string IndustryTypeNotExists {
            get {
                return ResourceManager.GetString("IndustryTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Type is saved successfully..
        /// </summary>
        internal static string IndustryTypeSavedSuccess {
            get {
                return ResourceManager.GetString("IndustryTypeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is saved successfully..
        /// </summary>
        internal static string ItemSavedSuccess {
            get {
                return ResourceManager.GetString("ItemSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location length should not be greater than 100 character..
        /// </summary>
        internal static string LocationLength {
            get {
                return ResourceManager.GetString("LocationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine description is deleted Successfully..
        /// </summary>
        internal static string MachineDescriptionDeletedSuccess {
            get {
                return ResourceManager.GetString("MachineDescriptionDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine description already exists..
        /// </summary>
        internal static string MachineDescriptionExists {
            get {
                return ResourceManager.GetString("MachineDescriptionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine description length should not be greater than 100 character..
        /// </summary>
        internal static string MachineDescriptionLength {
            get {
                return ResourceManager.GetString("MachineDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine description does not exist..
        /// </summary>
        internal static string MachineDescriptionNotExists {
            get {
                return ResourceManager.GetString("MachineDescriptionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine description is required..
        /// </summary>
        internal static string MachineDescriptionRequired {
            get {
                return ResourceManager.GetString("MachineDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine description is saved successfully..
        /// </summary>
        internal static string MachineDescriptionSavedSuccess {
            get {
                return ResourceManager.GetString("MachineDescriptionSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machining description is deleted successfully..
        /// </summary>
        internal static string MachiningDescriptionDeletedSuccess {
            get {
                return ResourceManager.GetString("MachiningDescriptionDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machining description already exists..
        /// </summary>
        internal static string MachiningDescriptionExists {
            get {
                return ResourceManager.GetString("MachiningDescriptionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machining description length should not be greater than 100 character..
        /// </summary>
        internal static string MachiningDescriptionLength {
            get {
                return ResourceManager.GetString("MachiningDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machining description does not exist..
        /// </summary>
        internal static string MachiningDescriptionNotExists {
            get {
                return ResourceManager.GetString("MachiningDescriptionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machining description is required..
        /// </summary>
        internal static string MachiningDescriptionRequired {
            get {
                return ResourceManager.GetString("MachiningDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machining description is saved successfully..
        /// </summary>
        internal static string MachiningDescriptionSavedSuccess {
            get {
                return ResourceManager.GetString("MachiningDescriptionSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES User Registration.
        /// </summary>
        internal static string MESUserRegistration {
            get {
                return ResourceManager.GetString("MESUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Award Feedback deleted successfully..
        /// </summary>
        internal static string NonAwardFeedbackDeletedSuccess {
            get {
                return ResourceManager.GetString("NonAwardFeedbackDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Award Feedback saved successfully..
        /// </summary>
        internal static string NonAwardFeedbackeSavedSuccess {
            get {
                return ResourceManager.GetString("NonAwardFeedbackeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Award Feedback already exists..
        /// </summary>
        internal static string NonAwardFeedbackExists {
            get {
                return ResourceManager.GetString("NonAwardFeedbackExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Award Feedback length should not be greater than 255 character..
        /// </summary>
        internal static string NonAwardFeedbackLength {
            get {
                return ResourceManager.GetString("NonAwardFeedbackLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Award Feedback does not exists..
        /// </summary>
        internal static string NonAwardFeedbackNotExists {
            get {
                return ResourceManager.GetString("NonAwardFeedbackNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Award Feedback is required..
        /// </summary>
        internal static string NonAwardFeedbackRequired {
            get {
                return ResourceManager.GetString("NonAwardFeedbackRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin deleted successfully..
        /// </summary>
        internal static string OriginDeletedSuccess {
            get {
                return ResourceManager.GetString("OriginDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin saved successfully..
        /// </summary>
        internal static string OrigineSavedSuccess {
            get {
                return ResourceManager.GetString("OrigineSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin already exists..
        /// </summary>
        internal static string OriginExists {
            get {
                return ResourceManager.GetString("OriginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin length should not be greater than 100 character..
        /// </summary>
        internal static string OriginLength {
            get {
                return ResourceManager.GetString("OriginLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin does not exists..
        /// </summary>
        internal static string OriginNotExists {
            get {
                return ResourceManager.GetString("OriginNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin is required..
        /// </summary>
        internal static string OriginRequired {
            get {
                return ResourceManager.GetString("OriginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No. already exists for current RFQ..
        /// </summary>
        internal static string PartNoExists {
            get {
                return ResourceManager.GetString("PartNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should not exceed 20 characters.
        /// </summary>
        internal static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordMinLength	Length of password should be minimim 5 characters.
        /// </summary>
        internal static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Password.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Please try again..
        /// </summary>
        internal static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully. You will receive an email notificaton shortly..
        /// </summary>
        internal static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined document type(s) added successfully..
        /// </summary>
        internal static string PredefinedDocumentTypeSavedSuccess {
            get {
                return ResourceManager.GetString("PredefinedDocumentTypeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference data is deleted successfully..
        /// </summary>
        internal static string PreferencesDeletedSuccess {
            get {
                return ResourceManager.GetString("PreferencesDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference data already exists..
        /// </summary>
        internal static string PreferencesExists {
            get {
                return ResourceManager.GetString("PreferencesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference data does not exist..
        /// </summary>
        internal static string PreferencesNotExists {
            get {
                return ResourceManager.GetString("PreferencesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference data is saved successfully..
        /// </summary>
        internal static string PreferencesSavedSuccess {
            get {
                return ResourceManager.GetString("PreferencesSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process deleted successfully..
        /// </summary>
        internal static string ProcessDeletedSuccess {
            get {
                return ResourceManager.GetString("ProcessDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process already exists..
        /// </summary>
        internal static string ProcessExists {
            get {
                return ResourceManager.GetString("ProcessExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process length should not be greater than 100 character..
        /// </summary>
        internal static string ProcessLength {
            get {
                return ResourceManager.GetString("ProcessLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process does not exists..
        /// </summary>
        internal static string ProcessNotExists {
            get {
                return ResourceManager.GetString("ProcessNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process is required..
        /// </summary>
        internal static string ProcessRequired {
            get {
                return ResourceManager.GetString("ProcessRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process saved successfully..
        /// </summary>
        internal static string ProcessSavedSuccess {
            get {
                return ResourceManager.GetString("ProcessSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project category is deleted successfully..
        /// </summary>
        internal static string ProjectCategoryDeletedSuccess {
            get {
                return ResourceManager.GetString("ProjectCategoryDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project category already exists..
        /// </summary>
        internal static string ProjectCategoryExists {
            get {
                return ResourceManager.GetString("ProjectCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project stage uses this category so it can not be deleted..
        /// </summary>
        internal static string ProjectCategoryIsInUse {
            get {
                return ResourceManager.GetString("ProjectCategoryIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project category length should not be greater than 100 character..
        /// </summary>
        internal static string ProjectCategoryLength {
            get {
                return ResourceManager.GetString("ProjectCategoryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project category does not exist..
        /// </summary>
        internal static string ProjectCategoryNotExists {
            get {
                return ResourceManager.GetString("ProjectCategoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project category is required..
        /// </summary>
        internal static string ProjectCategoryRequired {
            get {
                return ResourceManager.GetString("ProjectCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project category is saved successfully..
        /// </summary>
        internal static string ProjectCategorySavedSuccess {
            get {
                return ResourceManager.GetString("ProjectCategorySavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project stage is deleted successfully..
        /// </summary>
        internal static string ProjectStageDeletedSuccess {
            get {
                return ResourceManager.GetString("ProjectStageDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project stage already exists..
        /// </summary>
        internal static string ProjectStageExists {
            get {
                return ResourceManager.GetString("ProjectStageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project stage length should not be greater than 100 character..
        /// </summary>
        internal static string ProjectStageLength {
            get {
                return ResourceManager.GetString("ProjectStageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project stage does not exist..
        /// </summary>
        internal static string ProjectStageNotExists {
            get {
                return ResourceManager.GetString("ProjectStageNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project stage is required..
        /// </summary>
        internal static string ProjectStageRequired {
            get {
                return ResourceManager.GetString("ProjectStageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project stage is saved successfully..
        /// </summary>
        internal static string ProjectStageSavedSuccess {
            get {
                return ResourceManager.GetString("ProjectStageSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your quotation for this RFQ request has already been submitted. Thank you!.
        /// </summary>
        internal static string QuoteAlreadySubmitted {
            get {
                return ResourceManager.GetString("QuoteAlreadySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuoteDoneReport.
        /// </summary>
        internal static string QuoteDoneReportFileName {
            get {
                return ResourceManager.GetString("QuoteDoneReportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Done Report.
        /// </summary>
        internal static string QuoteDoneReportSheetName {
            get {
                return ResourceManager.GetString("QuoteDoneReportSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Done Report Template does not exists..
        /// </summary>
        internal static string QuoteDoneReportTemplateNotExists {
            get {
                return ResourceManager.GetString("QuoteDoneReportTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote part can not be saved due to some error..
        /// </summary>
        internal static string QuoteItemSavedFail {
            get {
                return ResourceManager.GetString("QuoteItemSavedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote part is saved successfully..
        /// </summary>
        internal static string QuoteItemSavedSuccess {
            get {
                return ResourceManager.GetString("QuoteItemSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote part data does not exist..
        /// </summary>
        internal static string QuotePartDataNotExists {
            get {
                return ResourceManager.GetString("QuotePartDataNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote saved successfully..
        /// </summary>
        internal static string QuoteSavedSuccess {
            get {
                return ResourceManager.GetString("QuoteSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote updated successfully..
        /// </summary>
        internal static string QuoteUpdatedSuccess {
            get {
                return ResourceManager.GetString("QuoteUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Quote has been saved successfully..
        /// </summary>
        internal static string QuoteUploadSuccess {
            get {
                return ResourceManager.GetString("QuoteUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exists..
        /// </summary>
        internal static string RecordNotExist {
            get {
                return ResourceManager.GetString("RecordNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks deleted successfully..
        /// </summary>
        internal static string RemarksDeletedSuccess {
            get {
                return ResourceManager.GetString("RemarksDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks already exists..
        /// </summary>
        internal static string RemarksExists {
            get {
                return ResourceManager.GetString("RemarksExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks length should not be greater than 200 character..
        /// </summary>
        internal static string RemarksLength {
            get {
                return ResourceManager.GetString("RemarksLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks does not exists..
        /// </summary>
        internal static string RemarksNotExists {
            get {
                return ResourceManager.GetString("RemarksNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks is required..
        /// </summary>
        internal static string RemarksRequired {
            get {
                return ResourceManager.GetString("RemarksRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks saved successfully..
        /// </summary>
        internal static string RemarksSavedSuccess {
            get {
                return ResourceManager.GetString("RemarksSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev Level updated successfully..
        /// </summary>
        internal static string RevLevelSuccess {
            get {
                return ResourceManager.GetString("RevLevelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQAnalysisReport.
        /// </summary>
        internal static string RFQAnalysisReportFileName {
            get {
                return ResourceManager.GetString("RFQAnalysisReportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Analysis Report.
        /// </summary>
        internal static string RFQAnalysisReportSheetName {
            get {
                return ResourceManager.GetString("RFQAnalysisReportSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfq Analysis Report Template does not exists..
        /// </summary>
        internal static string RFQAnalysisReportTemplateNotExists {
            get {
                return ResourceManager.GetString("RFQAnalysisReportTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQBusinessAnalysisReport.
        /// </summary>
        internal static string RFQBusinessAnalysisReportFileName {
            get {
                return ResourceManager.GetString("RFQBusinessAnalysisReportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Analysis Report.
        /// </summary>
        internal static string RFQBusinessAnalysisReportSheetName {
            get {
                return ResourceManager.GetString("RFQBusinessAnalysisReportSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ delete failed..
        /// </summary>
        internal static string RFQDeletedFailure {
            get {
                return ResourceManager.GetString("RFQDeletedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfq deleted Successfully..
        /// </summary>
        internal static string RFQDeletedSuccess {
            get {
                return ResourceManager.GetString("RFQDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Request for RFQ # %rfqNo%  sent to Suppliers.
        /// </summary>
        internal static string rfqMasterEmailSubject {
            get {
                return ResourceManager.GetString("rfqMasterEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQNonAwardReasonReport.
        /// </summary>
        internal static string RFQNonAwardReasonReportFileName {
            get {
                return ResourceManager.GetString("RFQNonAwardReasonReportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Non-Award Reason Report.
        /// </summary>
        internal static string RFQNonAwardReasonReportSheetName {
            get {
                return ResourceManager.GetString("RFQNonAwardReasonReportSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfq Non-Award Reason Report Template does not exists..
        /// </summary>
        internal static string RFQNonAwardReasonReportTemplateNotExists {
            get {
                return ResourceManager.GetString("RFQNonAwardReasonReportTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ does not exists..
        /// </summary>
        internal static string RFQNotExists {
            get {
                return ResourceManager.GetString("RFQNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Part(s) added successfully..
        /// </summary>
        internal static string RFQPartAddedSuccess {
            get {
                return ResourceManager.GetString("RFQPartAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Part deleted successfully..
        /// </summary>
        internal static string RFQPartDeletedSuccess {
            get {
                return ResourceManager.GetString("RFQPartDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Part does not exists..
        /// </summary>
        internal static string RFQPartNotExists {
            get {
                return ResourceManager.GetString("RFQPartNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Part is saved successfully..
        /// </summary>
        internal static string RFQPartSavedSuccess {
            get {
                return ResourceManager.GetString("RFQPartSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Part(s) saved successfully..
        /// </summary>
        internal static string RFQPartsSavedSuccess {
            get {
                return ResourceManager.GetString("RFQPartsSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Parts Supplier Wise Report.
        /// </summary>
        internal static string RFQPartsSupplierWiseReportFile {
            get {
                return ResourceManager.GetString("RFQPartsSupplierWiseReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ has been sent successfully to %supplierCompanyNames%..
        /// </summary>
        internal static string RFQSentSuccess {
            get {
                return ResourceManager.GetString("RFQSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Source deleted successfully..
        /// </summary>
        internal static string RFQSourceDeletedSuccess {
            get {
                return ResourceManager.GetString("RFQSourceDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Source already exists..
        /// </summary>
        internal static string RFQSourceExists {
            get {
                return ResourceManager.GetString("RFQSourceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Source length should not be greater than 100 character..
        /// </summary>
        internal static string RFQSourceLength {
            get {
                return ResourceManager.GetString("RFQSourceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Source does not exists..
        /// </summary>
        internal static string RFQSourceNotExists {
            get {
                return ResourceManager.GetString("RFQSourceNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Source is required..
        /// </summary>
        internal static string RFQSourceRequired {
            get {
                return ResourceManager.GetString("RFQSourceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Source saved successfully..
        /// </summary>
        internal static string RFQSourceSavedSuccess {
            get {
                return ResourceManager.GetString("RFQSourceSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ # %rfqNo% is Completed..
        /// </summary>
        internal static string rfqStatusCompleteEmailSubject {
            get {
                return ResourceManager.GetString("rfqStatusCompleteEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Supplier Part Quote Report.
        /// </summary>
        internal static string RFQSupplierPartsQuoteReportFile {
            get {
                return ResourceManager.GetString("RFQSupplierPartsQuoteReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Type deleted successfully..
        /// </summary>
        internal static string RFQTypeDeletedSuccess {
            get {
                return ResourceManager.GetString("RFQTypeDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Type already exists..
        /// </summary>
        internal static string RFQTypeExists {
            get {
                return ResourceManager.GetString("RFQTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Type length should not be greater than 50 character..
        /// </summary>
        internal static string RFQTypeLength {
            get {
                return ResourceManager.GetString("RFQTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Type does not exists..
        /// </summary>
        internal static string RFQTypeNotExists {
            get {
                return ResourceManager.GetString("RFQTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Type is required..
        /// </summary>
        internal static string RFQTypeRequired {
            get {
                return ResourceManager.GetString("RFQTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Type saved successfully. .
        /// </summary>
        internal static string RFQTypeSavedSuccess {
            get {
                return ResourceManager.GetString("RFQTypeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deleted successfully..
        /// </summary>
        internal static string RoleDeletedSuccess {
            get {
                return ResourceManager.GetString("RoleDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name already exists..
        /// </summary>
        internal static string roleNameExists {
            get {
                return ResourceManager.GetString("roleNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name does not exists..
        /// </summary>
        internal static string roleNameNotExists {
            get {
                return ResourceManager.GetString("roleNameNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role does not exists..
        /// </summary>
        internal static string RoleNotExists {
            get {
                return ResourceManager.GetString("RoleNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Object Privilege does not exists..
        /// </summary>
        internal static string RoleObjectPrivilegeNotExists {
            get {
                return ResourceManager.GetString("RoleObjectPrivilegeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Object Privilege saved successfully..
        /// </summary>
        internal static string RoleObjectPrivilegeSavedSuccess {
            get {
                return ResourceManager.GetString("RoleObjectPrivilegeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role saved successfully..
        /// </summary>
        internal static string RoleSavedSuccess {
            get {
                return ResourceManager.GetString("RoleSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following RFQ has been marked as complete, before the RFQ can be completely closed out, you must provide feedback on the outcome of the bid. Please do this within the next 10 business days..
        /// </summary>
        internal static string rqStatusCompleteEmailBodyFirstLine {
            get {
                return ResourceManager.GetString("rqStatusCompleteEmailBodyFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote part can not be added in to APQP due to some error..
        /// </summary>
        internal static string SAPItemSavedFail {
            get {
                return ResourceManager.GetString("SAPItemSavedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote part added successfully..
        /// </summary>
        internal static string SAPItemSavedSuccess {
            get {
                return ResourceManager.GetString("SAPItemSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Operation Description deleted successfully..
        /// </summary>
        internal static string SecondaryOperationDescDeletedSuccess {
            get {
                return ResourceManager.GetString("SecondaryOperationDescDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Operation Description already exists..
        /// </summary>
        internal static string SecondaryOperationDescExists {
            get {
                return ResourceManager.GetString("SecondaryOperationDescExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Operation Description length should not be greater than 100 character..
        /// </summary>
        internal static string SecondaryOperationDescLength {
            get {
                return ResourceManager.GetString("SecondaryOperationDescLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Operation Description does not exists..
        /// </summary>
        internal static string SecondaryOperationDescNotExists {
            get {
                return ResourceManager.GetString("SecondaryOperationDescNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Operation Description is required..
        /// </summary>
        internal static string SecondaryOperationDescRequired {
            get {
                return ResourceManager.GetString("SecondaryOperationDescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Operation Description saved successfully..
        /// </summary>
        internal static string SecondaryOperationDescSavedSuccess {
            get {
                return ResourceManager.GetString("SecondaryOperationDescSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can not be send. There is some error..
        /// </summary>
        internal static string SendEmailFail {
            get {
                return ResourceManager.GetString("SendEmailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent successfully..
        /// </summary>
        internal static string SendEmailSuccess {
            get {
                return ResourceManager.GetString("SendEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment is deleted successfully..
        /// </summary>
        internal static string ShipmentsDeletedSuccess {
            get {
                return ResourceManager.GetString("ShipmentsDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment does not exist..
        /// </summary>
        internal static string ShipmentsNotExists {
            get {
                return ResourceManager.GetString("ShipmentsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment saved successfully..
        /// </summary>
        internal static string ShipmentsSavedSuccess {
            get {
                return ResourceManager.GetString("ShipmentsSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is deleted successfully..
        /// </summary>
        internal static string StatusDeletedSuccess {
            get {
                return ResourceManager.GetString("StatusDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status already exists..
        /// </summary>
        internal static string StatusExists {
            get {
                return ResourceManager.GetString("StatusExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status length should not be greater than 100 character..
        /// </summary>
        internal static string StatusLength {
            get {
                return ResourceManager.GetString("StatusLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status does not exists..
        /// </summary>
        internal static string StatusNotExists {
            get {
                return ResourceManager.GetString("StatusNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required..
        /// </summary>
        internal static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is saved successfully..
        /// </summary>
        internal static string StatusSavedSuccess {
            get {
                return ResourceManager.GetString("StatusSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APQPStatus updated successfully..
        /// </summary>
        internal static string StatusUpdatedSuccess {
            get {
                return ResourceManager.GetString("StatusUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier has submitted a quote for RFQ # .
        /// </summary>
        internal static string submitQuoteEmailAdminSubj {
            get {
                return ResourceManager.GetString("submitQuoteEmailAdminSubj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for submitting the quote for RFQ # .
        /// </summary>
        internal static string submitQuoteEmailSupplierSubj {
            get {
                return ResourceManager.GetString("submitQuoteEmailSupplierSubj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is not able to delete any Supplier, As the selected Supplier(s) having one or more contacts..
        /// </summary>
        internal static string SupplierDeleteFail {
            get {
                return ResourceManager.GetString("SupplierDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error while submitting your quote..
        /// </summary>
        internal static string SupplierpartQuoteError {
            get {
                return ResourceManager.GetString("SupplierpartQuoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Quote is saved successfully..
        /// </summary>
        internal static string SupplierPartQuoteSavedSuccess {
            get {
                return ResourceManager.GetString("SupplierPartQuoteSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error while saving quote..
        /// </summary>
        internal static string SupplierQuoteError {
            get {
                return ResourceManager.GetString("SupplierQuoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Quote is saved successfully..
        /// </summary>
        internal static string SupplierQuoteSavedSuccess {
            get {
                return ResourceManager.GetString("SupplierQuoteSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier(s) deleted successfully..
        /// </summary>
        internal static string SuppliersDeletedSuccess {
            get {
                return ResourceManager.GetString("SuppliersDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier does not exist..
        /// </summary>
        internal static string SuppliersNotExists {
            get {
                return ResourceManager.GetString("SuppliersNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier is saved successfully..
        /// </summary>
        internal static string SuppliersSavedSuccess {
            get {
                return ResourceManager.GetString("SuppliersSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title already exists..
        /// </summary>
        internal static string TitleExists {
            get {
                return ResourceManager.GetString("TitleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title length should not be greater than 50 character..
        /// </summary>
        internal static string TitleLength {
            get {
                return ResourceManager.GetString("TitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total $ Quoted (month by month) Report.
        /// </summary>
        internal static string TotalDollarQuotedReportFile {
            get {
                return ResourceManager.GetString("TotalDollarQuotedReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point is deleted successfully..
        /// </summary>
        internal static string TriggerPointDeletedSuccess {
            get {
                return ResourceManager.GetString("TriggerPointDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point already exists..
        /// </summary>
        internal static string TriggerPointExists {
            get {
                return ResourceManager.GetString("TriggerPointExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point length should not be greater than 100 character..
        /// </summary>
        internal static string TriggerPointLength {
            get {
                return ResourceManager.GetString("TriggerPointLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point does not exist..
        /// </summary>
        internal static string TriggerPointNotExists {
            get {
                return ResourceManager.GetString("TriggerPointNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point is required..
        /// </summary>
        internal static string TriggerPointRequired {
            get {
                return ResourceManager.GetString("TriggerPointRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger point is saved successfully..
        /// </summary>
        internal static string TriggerPointSavedSuccess {
            get {
                return ResourceManager.GetString("TriggerPointSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to some reason, you will not be able to quote on this RFQ. Please contact help@mesinc.net..
        /// </summary>
        internal static string UniqueIdNotExist {
            get {
                return ResourceManager.GetString("UniqueIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file is blank. Please upload a valid file..
        /// </summary>
        internal static string UploadedFileIsBlank {
            get {
                return ResourceManager.GetString("UploadedFileIsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that in this uploaded file, the information, other than the required ones have been modified.&lt;br /&gt;Please download the RFQ file again and fill in the required values and upload it..
        /// </summary>
        internal static string UploadQuoteErrMsg1 {
            get {
                return ResourceManager.GetString("UploadQuoteErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the mandatory data in the excel file and upload..
        /// </summary>
        internal static string UploadQuoteErrMsg2 {
            get {
                return ResourceManager.GetString("UploadQuoteErrMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file is blank. Please upload a valid file..
        /// </summary>
        internal static string UploadQuoteErrMsg3 {
            get {
                return ResourceManager.GetString("UploadQuoteErrMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is deleted successfully..
        /// </summary>
        internal static string UserDeletedSuccess {
            get {
                return ResourceManager.GetString("UserDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists..
        /// </summary>
        internal static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name does not already exists..
        /// </summary>
        internal static string UserNameNotExists {
            get {
                return ResourceManager.GetString("UserNameNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        internal static string UserSavedSuccess {
            get {
                return ResourceManager.GetString("UserSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully..
        /// </summary>
        internal static string UserUpdatedSuccess {
            get {
                return ResourceManager.GetString("UserUpdatedSuccess", resourceCulture);
            }
        }
    }
}
