// <auto-generated />
namespace MES.Identity.Data.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NullableSupplierId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableSupplierId));
        
        string IMigrationMetadata.Id
        {
            get { return "201604261102003_NullableSupplierId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
